export const COALITION_UNITS = {
  OIL_RIG: {
    key: 'OIL_RIG',
    name: 'Oil Rig',
    icon: '🛢️',
    cost: 500,
    hp: 200,
    oilRate: 2,
    zone: 'COALITION_OIL',
    type: 'building',
  },
  TANKER: {
    key: 'TANKER',
    name: 'Tanker',
    icon: '⛽',
    cost: 200,
    hp: 100,
    speed: 60,
    zone: 'COALITION_DEPLOY',
    type: 'ship',
    scoreValue: 1,
    oilBonus: 500,
  },
  DESTROYER: {
    key: 'DESTROYER',
    name: 'Destroyer',
    icon: '🛥️',
    cost: 250,
    hp: 180,
    speed: 55,
    zone: 'COALITION_DEPLOY',
    type: 'ship',
    damage: 40,
    range: 200,
    fireRate: 1500,
    _spriteKey: 'spr_destroyer_hull',
  },
  AIR_DEFENSE: {
    key: 'AIR_DEFENSE',
    name: 'Air Defense',
    icon: '📡',
    cost: 600,
    hp: 250,
    damage: 80,
    range: 400,
    fireRate: 3000,
    zone: 'COALITION_LAND',
    type: 'building',
    unlockTime: 60000,
  },
  AIRFIELD: {
    key: 'AIRFIELD',
    name: 'Airfield',
    icon: '✈️',
    cost: 800,
    hp: 300,
    zone: 'COALITION_LAND',
    type: 'building',
    unlockTime: 180000,
  },
  COALITION_SUB: {
    key: 'COALITION_SUB',
    name: 'Submarine',
    icon: '🔱',
    cost: 450,
    hp: 120,
    speed: 50,
    damage: 80,
    range: 200,
    fireRate: 5000,
    sonarRange: 300,
    zone: 'COALITION_DEPLOY',
    type: 'ship',
    unlockTime: 180000,
  },
};

export const IRGC_UNITS = {
  OIL_RIG: {
    key: 'OIL_RIG',
    name: 'Oil Rig',
    icon: '🛢️',
    cost: 400,
    hp: 200,
    oilRate: 2,
    zone: 'IRGC_OIL',
    type: 'building',
  },
  MISSILE_LAUNCHER: {
    key: 'MISSILE_LAUNCHER',
    name: 'Missile Launcher',
    icon: '🚀',
    cost: 300,
    hp: 150,
    damage: 50,
    range: 350,
    fireRate: 2500,
    zone: 'IRGC_BUILD',
    type: 'tower',
  },
};

export const PROJECTILES = {
  MISSILE: {
    speed: 250,
    damage: 50,
    color: 0xff4444,
    radius: 4,
  },
  DESTROYER_SHELL: {
    speed: 350,
    damage: 40,
    color: 0x42a5f5,
    radius: 3,
  },
  INTERCEPTOR: {
    speed: 450,
    damage: 80,
    color: 0x00e5ff,
    radius: 3,
  },
  TORPEDO: {
    speed: 200,
    damage: 100,
    color: 0x00bcd4,
    radius: 4,
  },
  F22_BOMB: {
    speed: 350,
    damage: 100,
    color: 0xffab40,
    radius: 5,
  },
  FAST_BOAT_BULLET: {
    speed: 300,
    damage: 8,
    color: 0xff4444,
    radius: 2,
  },
};
