export const UPGRADES = {
  OIL_RIG: [
    {
      key: 'STORAGE',
      name: 'Storage',
      icon: '📦',
      desc: '+50% cap',
      maxLevel: 3,
      costs: [150, 250, 400],
    },
    {
      key: 'DRILL_RATE',
      name: 'Drill Rate',
      icon: '⛏',
      desc: '+30% output',
      maxLevel: 3,
      costs: [200, 350, 550],
    },
  ],
  TANKER: [
    {
      key: 'HULL',
      name: 'Hull Armor',
      icon: '🛡',
      desc: '+40% HP',
      maxLevel: 2,
      costs: [150, 300],
    },
    {
      key: 'ENGINE',
      name: 'Engine',
      icon: '⚡',
      desc: '+25% speed',
      maxLevel: 2,
      costs: [200, 400],
    },
  ],
  DESTROYER: [
    {
      key: 'DAMAGE',
      name: 'Armament',
      icon: '💥',
      desc: '+30% dmg',
      maxLevel: 3,
      costs: [200, 350, 500],
    },
    {
      key: 'ARMOR',
      name: 'Armor',
      icon: '🛡',
      desc: '+35% HP',
      maxLevel: 2,
      costs: [175, 350],
    },
    {
      key: 'FIRE_RATE',
      name: 'Fire Control',
      icon: '🎯',
      desc: '-20% cooldown',
      maxLevel: 2,
      costs: [250, 450],
    },
  ],
  AIR_DEFENSE: [
    {
      key: 'RANGE',
      name: 'Range',
      icon: '📡',
      desc: '+20% range',
      maxLevel: 2,
      costs: [300, 500],
    },
    {
      key: 'FIRE_RATE',
      name: 'Tracking',
      icon: '🎯',
      desc: '-20% cooldown',
      maxLevel: 2,
      costs: [350, 600],
    },
  ],
  AIRFIELD: [
    {
      key: 'ARMOR',
      name: 'Fortification',
      icon: '🛡',
      desc: '+35% HP',
      maxLevel: 2,
      costs: [400, 700],
    },
  ],
  COALITION_SUB: [
    {
      key: 'SONAR',
      name: 'Sonar Range',
      icon: '📡',
      desc: '+25% sonar',
      maxLevel: 2,
      costs: [300, 500],
    },
    {
      key: 'TORPEDO',
      name: 'Torpedoes',
      icon: '💥',
      desc: '+30% dmg',
      maxLevel: 2,
      costs: [350, 600],
    },
  ],
};
